### ISSUE TITLE
Request for Aaron Reed's Remembering

### ISSUE THREAD

**Issue by wmodes** [i7/extensions#118]
Reference: https://intfiction.org/t/the-mysteries-of-aaron-reeds-remembering-extension-and-a-solution/49840/3

Here's a request for an updated version of Aaron Reed's Remembering. It has been updated in many I7 versions. When last we looked, it wasn't running well even with 6M62.

I would attempt it, but it is beyond my knowledge.

**Comment by neroden** [comment]
I just got it working.  It's on the "master" branch and tested with Inform 9.2 (the bleeding edge version), but it might be possible to backport it to 9.1.

The way Aaron was implementing it doesn't work any more.  I implemented it using a lot more black magic (whch you can read in the source code).
