### ISSUE TITLE
Move in-progress / broken extensions to branches?

### ISSUE THREAD

**Issue by tunesmith** [i7/extensions#20]
Curious what others think - this can be closed as "wont fix" if it doesn't fit our charter.  But since there has been some confusion expressed about what this repo is for, what if we could say that the master branch had extensions that definitely work for 6L38 (or whatever the most recent version happens to be), while other in-progress extensions were in branches?

This is more a potential solution for the larger problem of, "how do we give Inform users a clear indication of where the most recent extensions are?"  I imagine there are better answers to that question.  :)  (Can we put the sources for the inform7 website up on github?)

**Comment by juhana** [comment]
I don't think it would be wise to start competing with the Public Library. The PL was made specifically to address the problem of the website extension collection being a grab-bag of all extensions ever made regardless of how out of date they are, and it's reasonable to assume it'll eventually grow to fulfill its purpose. The problem would be better solved by volunteering to the Inform team to update/maintain the Public Library instead.

Also, trying to keep the master branch clean of outdated extensions has the same problem as the I7 website: whenever a new version of Inform is released someone would have to go through and test every extension, and that's never going to happen.

**Comment by curiousdannii** [comment]
Yeah I don't think it would really help (although you can use branches for your own work if you like).

I've written the Graham about the possibility of making a new more advanced and automated repository system that would solve the current mess.
