### ISSUE TITLE
Glulx Text Effects: user style for hyperlinks?

### ISSUE THREAD

**Issue by alice-blue** [i7/extensions#30]
I'm not sure where this feature request should go, exactly, but...since there are user styles for most other things, could a user style be added for hyperlinks, so that game authors can change the color of the links? http://ifanswers.com/1218/does-change-user-style-hyperlinks-when-using-flexible-windows

**Comment by erkyrath** [comment]
The Glulx VM doesn't support this, sorry.

If you're putting a game online with Quixe or Parchment, you can customize the CSS file there.

**Comment by curiousdannii** [comment]
You can also change it in Gargoyle using a config file. As an example, see [Kerkerkruip.ini](https://github.com/i7/kerkerkruip/blob/master/Kerkerkruip.materials/Kerkerkruip.ini).
