### ISSUE TITLE
Simple Graphical Window documentation

### ISSUE THREAD

**Issue by alice-blue** [i7/extensions#33]
Simple Graphical Window has an error in the documentation--it uses the old "change x to y" syntax instead of "now x is y" in this example:

```
Carry out looking:
		change currently shown picture to the room illustration of the location;
		follow the current graphics drawing rule.
```

This is easy enough for me to change if you want me to upload it here, but thought I'd check first.

**Comment by curiousdannii** [comment]
Yeah definitely go ahead and just fix these things whenever you see them :)

**Comment by alice-blue** [comment]
Ok, done.

**Comment by alice-blue** [comment]
@curiousdannii I think you put the "change to" syntax back in with your most recent commit.

**Comment by alice-blue** [comment]
I changed that line back to the "now x is y" syntax again.

**Comment by curiousdannii** [comment]
oops, thanks for fixing it!
