### ISSUE TITLE
A pull/merge/push gone awry?

### ISSUE THREAD

**Issue by alice-blue** [i7/extensions#35]
Sorry guys! I meant to pull, merge, then push, but somehow I wound up causing changes to other people's extensions by accident. And I'm not sure how to fix it.

**Comment by harvimt** [comment]
is 6a42dab2e96fd79f12c00296f3246e042b04e466 the errant commit?

try `git revert 6a42dab2e96fd79f12c00296f3246e042b04e466; git push` if that's the problem.

**Comment by alice-blue** [comment]
6a42dab changed the correct file.

But [this one](https://github.com/i7/extensions/commit/73dfa29fa901d8523edbf5be335d1df3cedc1df9) seems to have made changes to Glk Object Recovery and Flexible Windows, neither of which I meant to touch.

**Comment by harvimt** [comment]
well then revert that one. :-)

**Comment by alice-blue** [comment]
I tried reverting but I think I'm doing something wrong. I will have to come back to this later. Thanks though.

**Comment by alice-blue** [comment]
Hmm. Even though [this merge](https://github.com/i7/extensions/commit/73dfa29fa901d8523edbf5be335d1df3cedc1df9) says that changes were made to Flexible Windows and Glk Recovery Object, when I go directly to [FW](https://github.com/i7/extensions/blob/73dfa29fa901d8523edbf5be335d1df3cedc1df9/Jon%20Ingold/Flexible%20Windows.i7x) and [GRO](https://github.com/i7/extensions/blob/73dfa29fa901d8523edbf5be335d1df3cedc1df9/Dannii%20Willis/Glk%20object%20recovery.i7x) in this repo, they don't show any new changes.

So...maybe it's just reflecting the changes that were made in my local repo when I merged, and not actually changing FW and GRO again in this repo. I didn't see a lot of merges when I scrolled down to see the repo history, though, so I'm not sure if this is how it's supposed to work.

**Comment by curiousdannii** [comment]
I'll take a look when I get home. It's probably fine.

**Comment by curiousdannii** [comment]
There's no problem, that's just how merge commits look sometimes.
