### ISSUE TITLE
GEP/FW: investigate rearrange events

### ISSUE THREAD

**Issue by curiousdannii** [i7/extensions#36]
Rearrange events don't seem to be passed to Flexible Windows. Are they not being handled by GEP correctly?

Once that is solved, then perhaps change when we call the redraw rules - not for text buffer windows?

**Comment by alice-blue** [comment]
Could this be related to the way resizing a window using Flexible Windows was leading to crashes in Spatterlight? https://github.com/i7/extensions/issues/31

**Comment by curiousdannii** [comment]
Probably not? But it would be worth checking when I fix this, if it also fixed that somehow.
