### ISSUE TITLE
Menus bug: true and false hidden-row entries treated alike

### ISSUE THREAD

**Issue by alice-blue** [i7/extensions#37]
@curiousdannii -- In your Menus extension, in lines 174, 216, and 325, the code checks for a hidden-row entry, but if it's present, treats it the same whether it's true or false. I think these should be changed from

    if there is a hidden-row entry:

to 

    if there is a hidden-row entry and the hidden-row entry is true:

I could change it myself but thought I should ask first.

**Comment by curiousdannii** [comment]
Good catch. Go ahead and edit it if you like!
