### ISSUE TITLE
Objects Matching Snippets is broken, and I have some unbroken code

### ISSUE THREAD

**Issue by MattWeiner** [i7/extensions#40]
The posted code for Objects Matching Snippets by Mike Ciul is broken. The critical relation "to be identified with" is defined nowhere in the extensions. (I think Mike took some code that was supposed to go after the already existing version one of Objects Matching Snippets and accidentally replaced the already existing version.) 

I have installed on my computer a version that seems to work. I'd like to branch the existing Objects Matching Snippets with this code, but I have no way to do this. (I tried to fork the extension and I wound up forking the entire extensions repository onto my site, and then I had to search for five minutes to find out how to delete the fork. For an open-source collaboration tool, Github sure doesn't seem to explain itself.)

So... I think I'd like to make a pull request with the working code? Anyone know how this works?

**Comment by mciul** [comment]
Hey Matt - I'm glad to see somebody working on this. I don't think any
of my extensions have worked with the current version Inform for
several years. I will take a closer look when I get the chance but I'm
having computer issues this week.

**Comment by MattWeiner** [comment]
Hey Mike,
Well, the version I have *is* working with the current Inform. Version 1 from the intfiction boards works with the current Inform too. I just think something weird happened with the current version 2. 

If it's OK with you I can just edit the file for Objects Matching Snippets to put in the code I have. It includes the Did the Player Choose rulebook but doesn't have any of the I6 inclusions for interrupting the turn sequence or anything like that. I'm not sure where it came from--maybe you e-mailed it to me sometime? Anyway, that wouldn't require any work from you.

I *think* if I edit the file you'd be able to get the code back using the history command but as I said I don't understand Github at all. Anyway it's also on eyeballsun so it would be retrievable from there.

**Comment by mciul** [comment]
If you edit, commit, and then push the code, it should be fine. One of my favorite features on Github is the "blame" button, which shows you which commit every line came from:

https://github.com/i7/extensions/blame/master/Mike%20Ciul/Objects%20Matching%20Snippets.i7x

Using "blame" is a good way to figure out when commits were applied, and of course who did them! That can be helpful if you actually do want to reverse a change. But rest assured, it's very difficult to lose something on Github forever.

I wish I could contribute more, but the computer I did all that work on is still not working. Keep me posted!

**Comment by MattWeiner** [comment]
OK, done, I think!

**Comment by mciul** [comment]
Thanks, Matt!

**Comment by MattWeiner** [comment]
...and for what it's worth, now that I've made the edit I see that when you do that there's an option to fork it instead of overwriting the main branch.

**Comment by mciul** [comment]
You did the right thing.
