### ISSUE TITLE
Simple Graphical Window: Public Library version has documentation error

### ISSUE THREAD

**Issue by alice-blue** [i7/extensions#46]
The version of SGW in the public library is version 9, which has a documentation error ("change to" instead of "now is".) Version 9/160121 corrected this. It also looks like there have been some FW related updates since then. @curiousdannii do you want to put one of the newer versions in the Public Library?

**Comment by curiousdannii** [comment]
Putting it in the PL would necessitate putting all the other extensions it depends on in the PL too, and unfortunately I don't have the time to bring them up to scratch.

**Comment by alice-blue** [comment]
Version 9/160121 of Simple Graphical Window doesn't depend on FW, does it?

**Comment by curiousdannii** [comment]
Oh true. Yes it should be submitted to the PL then. As it was your fix, would you like to submit it to the PL? :)

**Comment by alice-blue** [comment]
Ok, I've now emailed it.

**Comment by curiousdannii** [comment]
Thanks!
