### ISSUE TITLE
Version 12 of Tailored Room Description error

### ISSUE THREAD

**Issue by alice-blue** [i7/extensions#49]
According to a thread at intfiction.org (https://www.intfiction.org/forum/viewtopic.php?f=7&t=26232), the public library version of Tailored Room Description (version 12) gives an error when you try to include it in a project.

There are some more recent versions of Tailored Room Description on Github. Should one of those go in the Public Library instead? (I have not tested any of these--just reporting on what others have said.)

**Comment by angstsmurf** [comment]
This was fixed with 3bd8635 (in August 2016.)

**Comment by angstsmurf** [comment]
I realise now that this was a request to update the version currently in the public library, not the version here. I don't know if this is a good place for such requests, but that is not for me to decide. Sorry about that.

**Comment by neroden** [comment]
The new version is now in Graham's new Public Library.  I do not expect old versions of the public library to be updated so I guess that's done.
